# Generated by Django 5.1.4 on 2026-01-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="message",
            new_name="geo_message_point_i_7a2e75_idx",
            old_name="geo_messages_point_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="point",
            new_name="geo_points_locatio_4b1932_gist",
            old_name="geo_points_location_gist",
        ),
    ]
